version: "3.7"

services:
  server:
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9230:9230
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "debug"]
